version: "3"

services:
    chat:
        ports:
            - ${APP_PORT}:${PORT}
        build:
            context: .
            args:
                PUBLIC_URL: ${PUBLIC_URL}
        environment:
            - PORT=${PORT}
        tty: true
